### ISSUE TITLE
[BUG] BadZipFile and ValueError on Wafer Dataset

### ISSUE THREAD

**Issue by SewoongLee** [baraline/convst#49]
**Describe the bug**
There is data loading error in 'Wafer' dataset, while 'GunPoint' is ok.
![image](https://github.com/baraline/convst/assets/7731970/4a0d96eb-1b6b-42e9-80d6-52824584272d)

**To Reproduce**
You can reproduce the error by running following file.
https://1drv.ms/f/s!AuU5Lmr0utymk4IKdA1WNoxzkD0tNg

**Expected behavior**
Accuracy should be 1 on wafer dataset.

**Code example**
If applicable, add code example to help explain your problem.
Same as above

**Environment (please complete the following information):**
 - OS: [e.g. iOS] Google colab
 - Version of the convst package [e.g. 0.15]  : Latest (0.3.0)

**Additional context**

**Comment by baraline** [comment]
Hi, thanks for raising the issue. Next time you create an issue, please paste your code in markdown using \```python your code\```. Don't worry, the screenshot does the trick for this simple issue.

I can reproduce the issue on my side. The problem seem to be linked to an update of the source of the data (https://www.timeseriesclassification.com/dataset.php), and the link in the aeon package, which I use to pull the data, was not yet updated.

This should be fixed in the next version of aeon. In the meantime, you can edit the source file (in aeon 0.3) ```aeon/datasets/_data_loaders.py``` and modify the ```_load_dataset``` function. At line 493, you will find:

```python
url = "https://timeseriesclassification.com/Downloads/%s.zip" % name
```
Change it to:
```python
url = "https://timeseriesclassification.com/ClassificationDownloads/%s.zip" % name
```
And now this works as exepcted:
```python
X_train, X_test, y_train, y_test, _ = load_UCR_UEA_dataset_split('Wafer')
```

**Comment by baraline** [comment]
This should be now solved with the new release, updating aeon to >=0.4 should have the same effect.
